In [2]:
import pandas as pd

In [ ]:
df = pd.read_csv('ecommerce_sales_data.csv')

:

In [ ]:
df.head()

   Order Date Product Name     Category Region  Quantity  Sales  Profit
0  2024-12-31      Printer       Office  North         4   3640  348.93
1  2022-11-27        Mouse  Accessories   East         7   1197  106.53
2  2022-05-11       Tablet  Electronics  South         5   5865  502.73
3  2024-03-16        Mouse  Accessories  South         2    786  202.87
4  2022-09-10        Mouse  Accessories   West         1    509  103.28

:

In [ ]:
df.duplicated().sum()

0

:

In [ ]:
df.isna().sum()

Order Date      0
Product Name    0
Category        0
Region          0
Quantity        0
Sales           0
Profit          0
dtype: int64

:

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order Date    3500 non-null   object
 1   Product Name  3500 non-null   object
 2   Category      3500 non-null   object
 3   Region        3500 non-null   object
 4   Quantity      3500 non-null   int64
 5   Sales         3500 non-null   int64
 6   Profit        3500 non-null   float64
dtypes: float64(1), int64(2), object(4)
memory usage: 191.5+ KB

:

In [ ]:
df.columns = df.columns.str.replace(' ' , '-')

:

In [ ]:
df['Order-Date'] = df['Order-Date'].astype('date64[pyarrow]')

:

In [ ]:
df['Year'] = df['Order-Date'].dt.year

:

In [ ]:
df['Month'] = df['Order-Date'].dt.month

:

In [ ]:
df['Day'] = df['Order-Date'].dt.day

:

In [ ]:
df.sample()

,Order-Date,Product-Name,Category,Region,Quantity,Sales,Profit,Year,Month,Day
2303,2022-02-08,Smartwatch,Electronics,West,7,1806,129.6,2022,2,8

:

In [ ]:
df.drop(columns='Order-Date' , inplace=True)

:

In [ ]:
df.sample()

,Product-Name,Category,Region,Quantity,Sales,Profit,Year,Month,Day
2730,Mouse,Accessories,East,9,1233,346.9,2024,3,24

:

In [ ]:
df['Product-Name'].unique()

array(['Printer', 'Mouse', 'Tablet', 'Camera', 'Headphones', 'Smartwatch',
       'Monitor', 'Smartphone', 'Keyboard', 'Laptop'], dtype=object)

:

In [ ]:
X = df.drop(columns='Profit')

y = df['Profit']

:

In [ ]:
num_cols = df.select_dtypes(include='number').columns
cat_cols = df.select_dtypes(exclude='number').columns

:

In [ ]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X , y , random_state=42 , train_size= 0.8  ,shuffle=True)

:

In [ ]:
from sklearn.preprocessing import RobustScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeRegressor
from category_encoders.binary import BinaryEncoder

:

In [ ]:
num_cols

Index(['Quantity', 'Sales', 'Profit', 'Year', 'Month', 'Day'], dtype='object')

:

In [ ]:
cat_cols

Index(['Product-Name', 'Category', 'Region'], dtype='object')

:

In [ ]:
preprocessor = ColumnTransformer([
    ('scalling' , RobustScaler(),['Sales', 'Year' , 'Month' ,'Day']),
    ('encoding' , BinaryEncoder() , ['Product-Name' , 'Category' ,'Region'])
])

:

In [ ]:
pipeline = Pipeline([
    ('Preprocessor' , preprocessor),
    ('model' , DecisionTreeRegressor(min_samples_split=75))
])

:

In [ ]:
pipeline.fit(X_train , y_train)

c:\Users\Omar Saleh\Documents\Downloads\Lib\site-packages\sklearn\externals\_numpydoc\docscrape.py:420: UserWarning: Unknown section Example
  self[section] = content

Pipeline(steps=[('Preprocessor',
                 ColumnTransformer(transformers=[('scalling', RobustScaler(),
                                                  ['Sales', 'Year', 'Month',
                                                   'Day']),
                                                 ('encoding', BinaryEncoder(),
                                                  ['Product-Name', 'Category',
                                                   'Region'])])),
                ('model', DecisionTreeRegressor(min_samples_split=75))])

:

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

y_predict_train = pipeline.predict(X_train)
y_predict_test = pipeline.predict(X_test)

# MSE
mse_train = mean_squared_error(y_train, y_predict_train)
mse_test = mean_squared_error(y_test, y_predict_test)

# RMSE
# rmse_train = mean_squared_error(y_train, y_predict_train, squared=False)
# rmse_test = mean_squared_error(y_test, y_predict_test, squared=False)

# MAE
mae_train = mean_absolute_error(y_train, y_predict_train)
mae_test = mean_absolute_error(y_test, y_predict_test)

# R2 SCORE
r2_train = r2_score(y_train, y_predict_train)
r2_test = r2_score(y_test, y_predict_test)

print("MSE Train:", mse_train)
print("MSE Test:", mse_test)
print("*"*50)
# print("RMSE Train:", rmse_train)
# print("RMSE Test:", rmse_test)
print("MAE Train:", mae_train)
print("MAE Test:", mae_test)
print("*"*50)
print("R2 Score Train:", r2_train)
print("R2 Score Test:", r2_test)

MSE Train: 67613.50476419828
MSE Test: 97218.85773047464
**************************************************
MAE Train: 171.16034864824005
MAE Test: 208.13292069227825
**************************************************
R2 Score Train: 0.7340186424309421
R2 Score Test: 0.6162604172514337

:

In [ ]:
import pandas as pd

# 1 — Get feature names from preprocessor
feature_names = pipeline.named_steps['Preprocessor'].get_feature_names_out()

# 2 — Get model feature importances
importances = pipeline.named_steps['model'].feature_importances_

# 3 — Build DataFrame
fi_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importances
})

# 4 — Sort and show
fi_df = fi_df.sort_values(by='Importance', ascending=False)
fi_df.reset_index(drop=True, inplace=True)

print(fi_df)

                     Feature  Importance
0            scalling__Sales    0.983189
1         encoding__Region_2    0.003717
2            scalling__Month    0.003357
3   encoding__Product-Name_1    0.003301
4         encoding__Region_1    0.002477
5              scalling__Day    0.002145
6             scalling__Year    0.001638
7   encoding__Product-Name_2    0.000115
8         encoding__Region_0    0.000050
9   encoding__Product-Name_0    0.000010
10  encoding__Product-Name_3    0.000000
11      encoding__Category_0    0.000000
12      encoding__Category_1    0.000000

:

In [ ]:
import pandas as pd

# 1. Transform X
X_processed = pipeline.named_steps['Preprocessor'].transform(X)

# 2. Get feature names
feature_names = pipeline.named_steps['Preprocessor'].get_feature_names_out()

# 3. Convert to DataFrame
X_processed_df = pd.DataFrame(X_processed, columns=feature_names)

# 4. View processed data
X_processed_df.head()

,scalling__Sales,scalling__Year,scalling__Month,scalling__Day,encoding__Product-Name_0,encoding__Product-Name_1,encoding__Product-Name_2,encoding__Product-Name_3,encoding__Category_0,encoding__Category_1,encoding__Region_0,encoding__Region_1,encoding__Region_2
0,0.397436,0.5,1.000000,1.000000,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0
1,-0.314394,-0.5,0.833333,0.733333,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
2,1.045746,-0.5,-0.166667,-0.333333,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,-0.434149,0.5,-0.500000,0.000000,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
4,-0.514860,-0.5,0.500000,-0.400000,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0

:

In [ ]:
import pickle

:

In [ ]:
with open("decisiontree.pkl", "wb") as f:
    pickle.dump(pipeline, f)

:

In [ ]:
len(df['Month'].unique())

12

:

In [ ]:
with open("decisiontree.pkl", "rb") as f:
    model = pickle.load(f)

new_data = pd.DataFrame([{
    'Product-Name': 'Dress',
    'Category': 'Accessories',
    'Region': 'North',
    'Quantity': 8,
    'Sales': 1000,
    'Year': 2022,
    'Month': 5,
    'Day': 15}])

prediction = model.predict(new_data)
print(prediction)

[202.12253731]

:

In [ ]:
df.sample(1 , random_state=444)

,Product-Name,Category,Region,Quantity,Sales,Profit,Year,Month,Day
2737,Mouse,Accessories,North,8,2760,156.53,2022,5,15

:

In [ ]:
!pip install streamlit

Requirement already satisfied: streamlit in c:\users\omar saleh\documents\downloads\lib\site-packages (1.37.1)
Requirement already satisfied: altair<6,>=4.0 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (5.0.1)
Requirement already satisfied: blinker<2,>=1.0.0 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (1.6.2)
Requirement already satisfied: cachetools<6,>=4.0 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (8.1.7)
Requirement already satisfied: numpy<3,>=1.20 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (1.26.4)
Requirement already satisfied: packaging<25,>=20 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (24.1)
Requirement already satisfied: pandas<3,>=1.3.0 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<11,>=7.1.0 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (10.4.0)
Requirement already satisfied: protobuf<6,>=3.20 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (4.25.3)
Requirement already satisfied: pyarrow>=7.0 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (16.1.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (2.32.3)
Requirement already satisfied: rich<14,>=10.14.0 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (13.7.1)
Requirement already satisfied: tenacity<9,>=8.1.0 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (8.2.3)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (4.11.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (3.1.43)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (6.4.1)
Requirement already satisfied: watchdog<5,>=2.1.5 in c:\users\omar saleh\documents\downloads\lib\site-packages (from streamlit) (4.0.1)
Requirement already satisfied: jinja2 in c:\users\omar saleh\documents\downloads\lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in c:\users\omar saleh\documents\downloads\lib\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: toolz in c:\users\omar saleh\documents\downloads\lib\site-packages (from altair<6,>=4.0->streamlit) (0.12.0)
Requirement already satisfied: colorama in c:\users\omar saleh\documents\downloads\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\omar saleh\documents\downloads\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\omar saleh\documents\downloads\lib\site-packages (from pandas<3,>=1.3.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\omar saleh\documents\downloads\lib\site-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\omar saleh\documents\downloads\lib\site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\omar saleh\documents\downloads\lib\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\omar saleh\documents\downloads\lib\site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\omar saleh\documents\downloads\lib\site-packages (from requests<3,>=2.27->streamlit) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\omar saleh\documents\downloads\lib\site-packages (from requests<3,>=2.27->streamlit) (2024.8.30)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\omar saleh\documents\downloads\lib\site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\omar saleh\documents\downloads\lib\site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\omar saleh\documents\downloads\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\omar saleh\documents\downloads\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\omar saleh\documents\downloads\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\omar saleh\documents\downloads\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\omar saleh\documents\downloads\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\omar saleh\documents\downloads\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)
Requirement already satisfied: mdurl~=0.1 in c:\users\omar saleh\documents\downloads\lib\site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)
Requirement already satisfied: six>=1.5 in c:\users\omar saleh\documents\downloads\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)

:

: